### ISSUE TITLE
css伪类三角形

### ISSUE THREAD

**Issue by Tronzo** [Tronzo/Tech-loading#35]
```css
.down-triangle {
    width: 0;
    height: 0;
    border-top: 50px solid skyblue;
    border-right: 50px solid transparent;
    border-left: 50px solid transparent;
}
```
